
static char *spaceship[] = {
/* columns rows colors chars-per-pixel */
"63 71 6",
"  56",
". 63",
"X 4",
"o 49",
"O 7",
"# 0",
/* pixels */
"##########################XXXXXXXXXXX##########################",
"##########################           ##########################",
"##########################           ##########################",
"##########################OOOOXXXOOOO##########################",
"##########################OOOOXXXOOOO##########################",
"##########################OOOOXXXOOOO##########################",
"##########################OOOOXXXOOOO##########################",
"#########################OOOOOXXXOOOOO#########################",
"#########################OOOOOXXXOOOOO#########################",
"#########################OOOOOXXXOOOOO#########################",
"#########################OOOOOXXXOOOOO#########################",
"########################OOOOOOXXXOOOOOO########################",
"########################OOOOOOXXXOOOOOO########################",
"########################OOOOOOXXXOOOOOO########################",
"########################OOOOOOXXXOOOOOO########################",
"########################OOOOOOXXXOOOOOO########################",
"########################OOOOOOXXXOOOOOO########################",
"#######################OOOOOOOXXXOOOOOOO#######################",
"#######################OOOOOOOXXXOOOOOOO#######################",
"#######################OOOOXXXXXXXXXOOOO#######################",
"#######################OOOOX#######XOOOO#######################",
"#######################OOOOX#######XOOOO#######################",
"######################OOOOOX#######XOOOO#######################",
"######################OOOOOX#######XOOOO#######################",
"######################OOOOOX#######XOOOOO######################",
"######################OOOOOX#######XOOOOO######################",
"######################OOOOOX#######XOOOOO######################",
"######################OOOOOX#######XOOOOO######################",
"######################OOOOOX#######XOOOOO######################",
"######################OOOOXX#######XXOOOO######################",
"######################OOOOX#########XOOOO######################",
"######################OOOOX#########XOOOO######################",
"######################OOOOX#########XOOOO######################",
"######################OOOOX#########XOOOO######################",
"######################OOOOX#########XOOOO######################",
"######################OOOOX#########XOOOO######################",
"######################OOOOX#########XOOOO######################",
"######################OOOOXXXXXXXXXXXOOOO######################",
"######################OOOOOOOOOOOOOOOOOOO######################",
"#####################OOOOOOOOOOOOOOOOOOOOO#####################",
"########X###########OOOOOOOOOOOOOOOOOOOOOOO###########X########",
"#######XX###########OOOOOOOOOOOOOOOOOOOOOOO###########XX#######",
"######XXO###########OOOOOOOOOOOOOOOOOOOOOOO###########OXX######",
"######XXOO##########OOOOOOOOOOOOOOOOOOOOOOO##########OOXX######",
"#####XXOOO##########OOOOOOOOOOOOOOOOOOOOOOO##########OOOXX#####",
"#####XXOOO          OOOOOOOOOOOOOOOOOOOOOOO          OOOXX#####",
"####XXOOOOooooooooooOOOOOOOOOOOOOOOOOOOOOOOooooooooooOOOXX#####",
"###XXOOOOOooooooooooOOOOOOOOOOOOOOOOOOOOOOOooooooooooOOOOXX####",
"###XXOOOOOooooooooooOOOOOOOOOOOOOOOOOOOOOOOooooooooooOOOOXX####",
"##XXOOOOOOooooooooooOOOOOOOOOOOOOOOOOOOOOOOooooooooooOOOOOXX###",
"#XXOOOOOOOooooooooooOOOOOOOOOOOOOOOOOOOOOOOooooooooooOOOOOOXX##",
"#XXOOOOOOOoooooooooooooooooooooooooooooooooooooooooooOOOOOOOXX#",
"XXoOOOOOOOoooooooooooooooo           ooooooooooooooooOOOOOOOXX#",
"XooOOOOOOOoooooooooooooooo           ooooooooooooooooOOOOOOOooX",
" ooOOOOOOOoooooooooooooooo           ooooooooooooooooOOOOOOOoo ",
" ooOOOOOOOOOOOOoooooooXXoo           ooXXoooooooOOOOOOOOOOOOoo ",
" ooOOOOOOOOOOOOooooooooXo             oXooooooooOOOOOOOOOOOOoo ",
" ooOOOOOOOOOOOOooooooooX               XooooooooOOOOOOOOOOOOoo ",
"                       X               X                       ",
"                       X               X                       ",
"  #############        X               X        #############  ",
" ##############        X               X        ############## ",
"###############        X               X        ###############",
"###############       XX               XX       ###############",
"###############       X                 X       ###############",
"####################                       ####################",
"####################                       ####################",
"####################                       ####################",
"####################                       ####################",
"####################                       ####################",
"###############################################################"
};

/* XPM */
static char *c1[] = {
/* columns rows colors chars-per-pixel */
"126 115 3",
". 7",
"X 56",
"  0",
/* pixels */
"                                         XXXXXX                                                                               ",
"                                       XXXXXXXXXXXXXX                                                                         ",
"                                     XXXXXXXXXXXXXXXXXXXXXXX                                                                  ",
"                                    XX.XXXX...XXXXXXXXXXXXXXXXXXXXXX                                                          ",
"                                  XXX.XXXXXXXXXXXX..X.XXXXXXXXXXXXXXXXXXXXX                                                   ",
"                                XX.XX.......XXXXXXXXXXXX....XXXXXXXXXXXXXXXXXXXXXX                                            ",
"                                XXXXX...XXXX.X.X.....XXXXXX.XXXXXX..XXXXXXXXXXXXXXXXXXXXX                                     ",
"                               XXXXXX..XXXXXXXXXXXXX.X.X......XX.XXXXXXXXX...XXXXXXXXXXXXXX                                   ",
"                               XXXXX..XX.XX.XX.XXX.XXXXX.XX.X.......XXXX.X.X.XXXXX...XXXXXXXX                                 ",
"                              XXXXX...XXX.XXXXXX.XXXXX.XXXXXXXX..............X.XX.X.XXXX..XXXXX                               ",
"                              XX.XX.XXXXXXXX.XXXXXX.XXXXX.XX.X.X......................X.X.X.XXXXX                             ",
"                             XXXXX..XX.XX.XXXX.XX.XXXX.XXXXXXXXXXX.........................XX.XXXXX                           ",
"                             XX.XX.XXXXXXXX.XXXXXXXX.XXX.XX.XXX.X.X......X.X.X.XXXXXXXXXXX..XXX.XXXXX                         ",
"                            XX.XX.XXX.XX.XXXXXX.XX.XXXXXXXXXX.XXXXXXX.XXXXXXXXXX.X.XX.XX.XXX.XXXXXXXXXX                       ",
"                           XXX.X.XX.XXX.XXX.X.XXXXXX.X.XX.XXXXXX.XX.XXXX.X.XX.XXXXXX.XXXXX.X...XXXX.XXXXX                     ",
"                           XXXXX..XXXXXXX.XXXXXXX.XXXXXXXXX.XX.XXXXXXX.XXXXXXX.XX.XXXXX.XXXXXX..XXXXXXXXXXX                   ",
"                          XXXXX.XXXX.XXXXXXX.XX.XXXX.XX.XXXXXXXXX.XX.XXXX.XX.XXXXXX.XXXXXX.XXXX..XXXXXX.XXXXX                 ",
"                          XXXXX..XXXXX.XX.XXX.XXXX.XXXXXXX.X.XX.XXXXXXX.XXXXXXXX.XXXX.XX.XXX.XXXX.XXXXXXXXXXXX                ",
"                         XXXXXXXXX.XX.XXXXXXXXXX.XXXX.XX.XX.X.XXXX.XX.XXXX.XX.XXXX.XXXXXXXXXXX.XX.X.XXXXXXXXXXX               ",
"                        XXXXXX..XXXXXXXX.XX.XX.XXXX.XXXXXX....XX.XXXXXXXXXXXXXX.XXXXX.XX.XX.XXXXXXX..XXXXXXX.XX               ",
"                        XX.XXXXXXX.XX.XXXX.XXXXXX.XXXX.X.....X.XXXX.XX.X.XX.XXXXX.XX.XXXXX.XXX.XX.XXX..XXXXXXXXX              ",
"                       XX.XXX..XXXX.XXX.XXXXXX.XXXXX.XXXX.....XXX.XXXXXXX.XXXX.XXXXXXXX.XXXX.XXXXXX.XX..XXXXXXXX              ",
"                      XXX.XXXXXX.XXXXXXXX.XX.XXX.XXXXXX......XX.XXXX.XXXXXXX.XXX.XX.XXXXXXXXXXX.XXXXXX.XXXXXXXXX              ",
"                      XX.XXX..XXXXX.XX.XXXXXXXXXXX.XX.XX......XXXX.XXXX.XX.XXX.XX.XX.X.X.X.XX.XXX.X.X.X...XXXXXXX             ",
"                     XXX.XXX.XX.XX.XXXXX.XX.XX.XXXXXXXX.X....XX.XXXXX.XXXXXX..X......X..X.X.X.X.XX.X.......XXX.XX             ",
"                     XXXXX...XXXXXXXX.XXXXXX.XXXX.XX.XXX......XX.XX.XXXX.X.................................XXXXXX             ",
"                    XXXXXXX.XXX.XX.XXXX.XX.XXXX.XXXXXXXXX....XXXXXXXX.....................................X.XXXXXX            ",
"                   XXXXXX..XXXXXXXXX.XXXXXXXX.XXXXX.XX.XX....X.XX.X..X.....................................XXXXXXX            ",
"                   XXXXXX.XX.XX.XX.XXX.XX.XXXXXX.XXXX.XXX.....X.........................................XXX.XXXXXX            ",
"                  XXXXXX..XXX.XXXXXXXXXXXXX.XX.XXX.XXXX.XX.......................X.....................X..X.XXX.XX            ",
"                 XXX.XXX.XXXXXX.X.XX.XX.XXXXXXXXX.XXXXXXX.........................X...................X.XX.X.XXXXXX           ",
"                XXX.XXX.XXX.X...XXXXXXXXX.XX.XX.XXXX.X.XX.........................X...................X.X.X.XXXXXXX           ",
"                XXXXXXX.XX.X....XX.XX.XXXXX.XXXXXX.XXXXX.X.......................XXX................XX.X.X.X..XXXXX           ",
"               XX.XXXX...X.......XX.XXX.X.XXXXX.XXXXX.XXX.......................X.XX..............X..X.X.X....XXXXXX          ",
"              XXX.XXX............XXXXXXXXXXX.XXXX.XXXXXX........................XXX.X.............X.X.X........XXXXXX         ",
"             XXXXXXX..............X.XX.XX.XXXX.XXXX.X.XXX......................X.XXXX............X.X.X.X.....X.XXXXXX         ",
"            XXX.XXX.............XXXXX.XXXXX.XXXX.XXXXXXX......................XXXX.X.............X.X.X.....XXX..XXXXXX        ",
"           XXX.XXX...............XXXXXXX.XXXX.XXX.XXX.XXX.....................X.XXXX.............X.X.X......XXX.XXXXXX        ",
"          XXXXXXX...............XX.XXX.XXXX.XXXXXXX.XXXX.....................XXXXX.X.............X.X.X....XXXX...XXXXXX       ",
"         XXX.XXX......XX.......X.XXX.XXXX.XXXXXX.XXXX.XXX...................XXX.XXX...............X.X.....XXXXX.XXXXXXX       ",
"         XXXXXX....XXX..........XXXXXXX.XXXX.X.XXXXXXXXX...................XX.XXXX.X.............X.X.....XXX.XX...XXX.XX      ",
"        XXXXXX...XXX.X..........XX.XX.XXXX.XXXXXXX.X.XX.X.................X.XXXX.XX..............X.XX...XX.XXXXX.XXXXXXX      ",
"       XXX.XX.XXXXX.X..........XXXXXXXXX.XXXX.XX.XXXXX.X..............X.XXXXXX.XXX...............X.X....XXXXX.X.X.XXXX.XX     ",
"      XXXXX.XX.XX.XX...........X.XX.XX.XXXXXXX.XXXXX.XX..........X.XXXXXX.XX.XXXXX...............X.X...XXX.XX...X.XXXXXXX     ",
"      XXXX.XXXXXXX............XXXXXXX.XXX.X.XXXXX.XXX.............XX.XX.XXX.XXX.X.................X.....X.XX...X.X.XXXXXX     ",
"      XXXX..X.XX.X.............XXX.XXXXXXXXXXX.XXX.XX...............X.XXX.X.X..X.................X.X.....X....X.X.XXXXXXXX    ",
"     XXX..XXXXX.X............XXX.XXX.XX.XXX.XXXX.XXX.................X............................X...........X.X.X.XXX.XX    ",
"     XX.X..X.XXX.............XXXXXXXXXXXX.XXX.XXXXX...............................................X...........X.X.XXXXX.XX    ",
"     XXXX.XXXX.............XXX.XX.XX.XX.XXXXXXX.XX..........XXXX.............................................X.X.X.XXXXXXXX   ",
"     XXXX..XXXX.............XXXXXXXXX.XXXXX.X.XXXX.........XXXXXXX.X..............................X.X..X....X.X.X.XXXXXXXXX   ",
"    XXXXX.XX.X............XXXX.XX.XXXXXX.XXXXXXX.........XXXX.XXXXXX.X..............................X.X.XX.X.X.X.X.XXXXXXXX   ",
"    XX.XX.XXXXX...........XX.XXXXXX.XX.XXXX.XX.XX......X.XXXXXX.X.X.X.X.............................X.X.X.X.X.X.X.XXXXXXXXX   ",
"    XXXXXXX.XX...........XXXXXX.XXXXXXXXX.XXXXX.......X.XX.X.........................................X.X.X.X.X.XX.XXXXXXXXX   ",
"    XXXXX.XXXX..........XXXX.XXXX.X.XX.XXXXXX.X.......XXX.X..........................................X.X.X.XX.X.X.XXXXXXXXX   ",
"   XXXXX.XXX.X..........X.X.XX.X.XXXX.XX.X.X.X......X.................................................X.X.X.X.X.X.XXXXXXXX    ",
"   XX.XX.X.XXX........................................................................................X.X.X.X.X.X.XXXXX.XX    ",
"   XXXXX.XXXX..........................................................................................X.X.X.X.X.X.XXXX.XX    ",
"   XXXX..XX.XX.........................................................................................X.X.X.X.X.XXXXXXXXX    ",
"  XXXXX.XXXX............................................................................................X.X.X.X.X.XXXXXXXX    ",
"  XX.X..XX.X............................................................................................X.X.X.X.X.XXXXX.XX    ",
"  XXXX.XXX...............................................................................................X.X.X.X.X.XXXXXXXX   ",
"  XXXX.X.X................................................................................................X.X.X.X.XXXXXXXXX   ",
" XXXX.XXX.................................................................................................X.X.X.X.X.XXXXXXX   ",
" XX.X.X....................................................................................................X.X.X.X.XXXXXXXXX  ",
" XXXXX....................................................................................................X.X.X.X.X.XXXXXXXX  ",
" XX...X...................................................................................................X.X.X.X.X.XXXXX.XX  ",
"XXX......................................................................................................X.X.X.X.X.X.XXXXXXXX ",
"XX.X......................................................................................................X.X.X.X.X.XXXXXXXXX ",
"XXXXX...................................................................................................XX.X.X.X.X.X.XXXXXXXX ",
"XXXX..................XX..................................................................................X.X.X.X.X.X.XXXXXXXX",
"XXXX..................XX...............................................................................XXX.X.X.X.X.X.X.XXXX.XX",
"XX.X...................XXX..............................................................................X.X.X.X.X.X.X.XXXXXXXX",
"XXXX.................XXXXX...................................................X........................XX.X.X.X.X.XX.X.XXXXXXXX",
"XXXX..................XX.XXX....................................X..........XXXX.........................X.X.X.X.X.X.XXXXXXX.XX",
" XX..................XXXXXX.X...................................XXX.....XXXX.X.......................XXX.X.X.X.X.X.XXXXXXXXXXX",
" XXXX...............XXXX.XXXX..................................XX.XXX.XX.XXXXXX.......................X.X.X.X.X.X.XXXXXXXXXXX ",
"  XX..............XXX.XXXX.XX.XX...............................XXXXX.XXXXX.XX.XX....................XX.X.X.X.X.X.XXXXXXXXXXX  ",
"  XX.X...........X.XXX.X.XX.XXX...............................X.XX.XXXX.XXXXXX......................X.X.X.X.X.X.XXXXXXXX.XX   ",
"   XX...........XXXX.XX.X....X...............................XXXXXXXXXXXXX.XXX.....................X.X.X.X.X.X.XXXXXXXXX.XX   ",
"   XX.X........XX.X.X.........XX..............................X.XX.XX.XX.XXX.XX.....................X.X.X.X.X.XXXXXXXXXXXX    ",
"    XX.X.....XX..X..........................................XXXXXXXX.XXXXXXXXX....................XX.X.X.X.X.XXXXXXXXXXXX     ",
"    XX.X..............X.X.X............................X.XXXX.XXX.XXXXXX.XX.X.......X.X.X.X.X.X.X.X.X.X.X.X.XXXXXXXXXXXXX     ",
"    XXXXX..........X.X.X.X.X.X.................X.XXXXXXXXXX.XXX.XXX.XX.XXX.........X.X.XX.XX.X.XX.X.X.X.X.XXXXXXXXXXX.XX      ",
"     XX.X........X.X.X.X.X.X.X................X.X.X.XXXXX.XXXXXXXXXXXXX.X.........X.X.X.X.X.X.X.X.X.X.X.X.XXXXXXXXXXXXX       ",
"     XXXXX.....X.X.X.X.X.X.X.X.X.X...............X.XX.X.XXXX.XX.X.XX.X.X........X.X.X.X.X.X.X.X.X.X.X.X.XXXXXXXXXXXXXX        ",
"      XXXXXX.XX.X.X.X.X.X.X.X.X.X.X....................X.X.XX.XXXXXXX...........X.X.X.X.X.X.X.X.X.X.X.X.XXXXXXXXXXXXXX        ",
"      XXXXXXX.X.X.X.X.XX.X.X.X.X.X.X.......................X.XX.XX............XX.X.X.X.X.X.X.X.X.X.X.X.XXXXXXXXXXX.XX         ",
"       XXXXX.X.X.X.X.X.X.XX.X.X.X.X.XX.X.......................X............X.X.X.X.XX.X.X.X.X.X.X.X.XXXXXXXXXXXX.XX          ",
"       XXXXXXX.X.X.X.X.X.X.X.X.X.X.X.X.X.XX.X..............................X.X.X.X.X.X.X.X.X.X.X.X.X.XXXXXXXXXXXXXXX          ",
"       XXXXXXXX.XX.X.X.X.X.X.X.X.X.X.X.X.X.X.XXX.X.X......................X.X.X.X.X.X.X.X.X.XX.X.X.XXXXXXXXXXXXXXXX           ",
"        XX.XXX.X.X.X.X.X.X.X.X.XX.X.X.X.X.X.X..X.X.X.X.X................XX.X.X.X.X.X.X.X.X.X.X.X.X.XXXXXXXXXXXXXXX            ",
"        XXXXXXXX.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XX.X.X.X.X.XXXX.X.X.......X.X.X.X.X.X.X.X.X.X.X.X.X.XXXXXXXXXXXXX.XX             ",
"         XX.XXX.X.X.X.X.X.X.X.X.X.X.X.XX.X.X.X.X.X.X.X.X..X.X.X.X.X.XXX.X.X.X.X.XX.X.X.X.X.X.X.XXXXXXXXXXXXXXXXXX             ",
"         XX.XXXX.X.X.X.X.X.X.X.X.X.XX.X.X.X.X.X.X.X.X.X.XX.X.X.X.X.X..X.X.X.X.XX.X.XX.XX.XXXXXXXXXXXXXXXXXXXXXXX              ",
"          XX.XXXX.X.X.X.X.X.X.X.X.X..X.X.X.X.X.XX.X.X.X.X.X.X.X.X.X.XX.X.XX.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX               ",
"          XX.XXXXX.X.X.X.X.X.X.XX.XX.X.X.X.X.X.X.X.XX.X.X.X.X.X.X.X.X.X.X..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XX                ",
"           XX.XXXX.X.X.XXXXXXXXXXXXXXXX.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XX                ",
"           XX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.X.X.X.X.X.X.X.XX.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                 ",
"           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XX.X.X.X.X.X.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                  ",
"            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X.X.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                  ",
"            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XX                   ",
"             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                    ",
"             XXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                     ",
"              XXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                     ",
"               XXXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XX                      ",
"                              XXXXXXXX..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..XXXXX.XXXXXXXXXXXXXX.XX                       ",
"                                  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXX..XXXXXXXXXXX                        ",
"                                       XXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     XXXXXXXX..XXXXXXX                        ",
"                                          XXXXX.XXXXXXXXXXXXXXXXXXXX.XXXXXXX             XXXXXXXXXXXX                         ",
"                                            XXXXX.XXXXXXXXXXXXXX.XXXXXXX                      XXXXXX                          ",
"                                               XXXXXXXXXXXXXX.XXXXXXX                                                         ",
"                                                 XXXX.XXX.XXXXXXX                                                             ",
"                                                   XXXXXXXXXX                                                                 ",
"                                                     XXXXX                                                                    ",
"                                                                                                                              "
};


/* XPM */
static char *bullet[] = {
/* columns rows colors chars-per-pixel */
"10 10 3",
"  63",
". 0",
"X 46",
/* pixels */
"... XX ...",
". XXXXXX .",
".XXXXXXXX.",
" XXXXXXXX ",
"XXXXXXXXXX",
"XXXXXXXXXX",
" XXXXXXXX ",
".XXXXXXXX.",
". XXXXXX .",
"... XX ..."
};





